# Generated by Django 5.2.7 on 2025-11-05 06:40

import sharefiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharefiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(max_length=255, upload_to=sharefiles.models.user_file_path),
        ),
    ]
